title: David Lang Site
email: davidnathanlang@stanford.edu
description: David Lang Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidnathanlang.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
# for google analyitcs ID
ga_id:

#social media
twitter: davidnlang

disqus:
  shortname: davidnathanlang

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-paginate
  - jekyll-sitemap

excerpt_separator: <!--more-->

# specifies how many items should be displayed per page in the blog
paginate: 6
paginate_path: "/blog/page:num/"
recent_post_limit: 4

sass:
  style: compressed # possible values: nested expanded compact compressed

defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # previously `post` in Jekyll 2.2.
  values:
    permalink: "/blog/:title"